# Generated by Django 5.0.4 on 2024-07-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name_plural': 'Testimonies'},
        ),
        migrations.AddField(
            model_name='testimony',
            name='avatar',
            field=models.ImageField(blank=True, null='True', upload_to='avatar/'),
            preserve_default='True',
        ),
    ]
