# Generated by Django 5.0.4 on 2024-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_paid_amount_order_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
